services:
  nginx:
    image: dockerhub.timeweb.cloud/nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .docker/nginx/conf.d/:/etc/nginx/conf.d/
      - .docker/nginx/logs/:/var/log/nginx/
      - .:/var/www
    depends_on:
      - app

  mariadb:
    image: dockerhub.timeweb.cloud/mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: ecomcom_usr
      MARIADB_PASSWORD: ecomcom_password
      MARIADB_DATABASE: ecomcom_services

  phpmyadmin:
    image: dockerhub.timeweb.cloud/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_USER: ecomcom_usr
      PMA_PASSWORD: ecomcom_password
      UPLOAD_LIMIT: 100000000

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass root

  app:
    build: .docker/php-fpm
    restart: unless-stopped
    volumes:
      - .:/var/www
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: ecomcom_services
      DB_USERNAME: ecomcom_usr
      DB_PASSWORD: ecomcom_password

      REDIS_HOST: redis
      REDIS_PASSWORD: root
      REDIS_PORT: 6379
    depends_on:
      - redis
      - mariadb